### ISSUE TITLE
Signer Offering Metadata Key Names

### ISSUE THREAD

**Issue by sebastianmontero** [smartvaults/smartvaults#100]
The names of the keys for the signer offering metadata event should be:

- temperature (possible values: warm, cold, air-gapped)
- response_time (time in minutes?)
- device_type (the brand of the cold card, view the comment below)
- cost_per_signature
- yearly_cost_basis_points(percentage of the vault balance that should be charged)
- yearly_cost

**Comment by mgravitt** [comment]
Valid values for Device type could be any string, but we should offer the below in the UI:  
- Coldcard
- BitBox02
- Ledger
- Mobile device
- Desktop/laptop device
- Cloud-based
- Other: <enter text>
- Undisclosed

**Comment by mgravitt** [comment]
@sebastianmontero I think the costs should be annual instead of monthly, even though fees may be charged monthly. It makes it easier to calculate the cost in days. Most recurring fees I've seen have been yearly basis points (100, or 1% per year).
