### ISSUE TITLE
Key Agents support [DRAFT]

### ISSUE THREAD

**Issue by mgravitt** [smartvaults/smartvaults#97]
Key agents are users/services that protect and use a key to sign transactions at hire of the subscriber. Key agents have a general profile and 1:n extended public keys associated with their profile. 

> What data on the key agent profile is public? IMO, it's like a public social media profile. 

A key agent may share their key with users (or vice versa), and either party can create vaults with both participants. In many cases, the key agent will be the vault creator. 

The key agent profile can be like a normal nostr profile with additional metadata, either key/value pairs or attributes like jurisdiction, social media links, etc. 

Each key will have metadata, either key/value pairs, or attributes like temperature, response time, device type, cost per signature, monthly cost in basis points, etc. 

> What data on the key agent profile is public? IMO, it's like a public social media profile. 

Key agents should be able to communicate with their clients directly in the app using Nostr DM protocols. 

Key agents should be able to post public events to the Nostr timeline and have them appear with their profile in the app.

When new activity occurs (key shares, proposals, etc), users get a DM style message and push notification.

**Comment by sebastianmontero** [comment]
@mgravitt how do you envision the monthly cost being charged?

**Comment by mgravitt** [comment]
@sebastianmontero the monthly charge could be paid directly from the vault. The price could be in basis points (like 1% per year), a monthly flat rate, or a per signature fee. I think the basis points pricing is most relevant based on the research. It would calculate [days since last payment] / 365 * 0.01 to get the payment required to "catch up" on a subscription at any point.

**Comment by sebastianmontero** [comment]
@mgravitt but would you charge the accumulated fees when the vault owner does a transaction?

**Comment by mgravitt** [comment]
It'll likely be a standalone transaction, once per month

**Comment by sebastianmontero** [comment]
Transaction fees could be an issue with a monthly transaction don't you think?

**Comment by mgravitt** [comment]
Yes, if it is auto-calculated since the last key agent fee, it doesn't have to be monthly, but it would just calculate the amount since the last key agent fee payment
