### ISSUE TITLE
Key Agent additional profile key names

### ISSUE THREAD

**Issue by sebastianmontero** [smartvaults/smartvaults#99]
The names of the keys for the additional properties in the key agent profile should be:

- jurisdiction
- x
- facebook
- linkedin
- smartvaults_nip05 (nip05 specific for smartvaults where will add the agents approved by us)

**Comment by mgravitt** [comment]
I think we should also add `website`

All properties should be optional

**Comment by sebastianmontero** [comment]
website is already part of the base profile properties
